version: '3'
services:
  tf:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./wheels:/wheels
      - ./binaries:/binaries
    environment:
        - TF_VERSION_GIT_TAG=v1.8.0
        - TF_COMPILATION_WITH_GPU=1
